version: '3.2'

services:

    core:
        image: javclub/core:latest
        volumes:
            - ./config:/usr/app/config
        environment:
            - NODE_ENV=dev
            - TZ=Asia/Shanghai
        restart: unless-stopped
        networks:
            - docker-lemp_default

networks:
    docker-lemp_default:
        external: true
